###
GET http://{{HostAndPort}}/admin/add-products?keyword=得力 文具&typeName=办公用品

###
GET http://{{HostAndPort}}/admin/add-products?keyword=洗发水&typeName=日用百货

###
GET http://{{HostAndPort}}/admin/add-products?keyword=沐浴露&typeName=日用百货

###
GET http://{{HostAndPort}}/admin/add-products?keyword=微单&typeName=摄影器材

###
GET http://{{HostAndPort}}/admin/add-products?keyword=摄影三脚架&typeName=摄影器材

###
GET http://{{HostAndPort}}/admin/add-products?keyword=打印机&typeName=办公用品

###
GET http://{{HostAndPort}}/admin/add-products?keyword=t恤男&typeName=服装服饰

###

GET http://{{HostAndPort}}/admin/add-products?keyword=洗发水控油&typeName=日用百货

###
