spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zshop?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin123456
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.xmlvhy.shop.admin.pojo
  config-location: classpath:mybatis/mybatis-config.xml